# Generated by Django 4.1.7 on 2023-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcode_text', models.CharField(blank=True, max_length=200)),
                ('itemcode_text', models.CharField(max_length=50)),
                ('drowcode_text', models.CharField(blank=True, max_length=200)),
                ('type_text', models.CharField(blank=True, max_length=10)),
                ('heat_dissipate_deci', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delta_temp_deci', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rth_deci', models.DecimalField(decimal_places=5, max_digits=8)),
                ('cooling_text', models.CharField(blank=True, max_length=50)),
                ('ambient_intf', models.IntegerField()),
                ('ambient_intt', models.IntegerField()),
                ('weight_deci', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_text', models.CharField(blank=True, max_length=100)),
                ('basesize_text', models.CharField(blank=True, max_length=100)),
                ('mold_text', models.CharField(blank=True, max_length=30)),
                ('product_type_text', models.CharField(blank=True, max_length=50)),
                ('pipe_num_int', models.IntegerField()),
                ('fins_num_int', models.IntegerField()),
                ('client_text', models.CharField(blank=True, max_length=200)),
                ('project_text', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
